[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]
evm_version = "shanghai"
ast = true
build_info = true
extra_output = ["storageLayout"]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true

[rpc_endpoints]
11155111 = "${SEPOLIA_RPC_URL}"
31337 = "${ANVIL_RPC_URL}"
1 = "${MAINNET_RPC_URL}"

534352 = "${SCROLL_RPC_URL}"
42161 = "${ARBITRUM_RPC_URL}"
10 = "${OPTIMISM_RPC_URL}"
59144 = "${LINEA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
