name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Add GitHub to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          repository: jigsaw-finance/jigsaw-protocol-v1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: forge --version

      - name: Create .env file
        run: |
          touch .env
          echo MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }} >> .env
          echo DEPLOYER_PRIVATE_KEY=${{ secrets.DEPLOYER_PRIVATE_KEY }} >> .env

      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge scripts
        run: forge test --match-path "test/scripts/*"
      - name: Run Forge Utils tests
        run: forge test --match-path "test/utils/*"
      - name: Run Forge Ataker tests
        run: forge test --match-path "test/staker/*"
      - name: Run Forge Aave tests
        run: forge test --match-path "test/aave/*"
      - name: Run Forge Dinero tests
        run: forge test --match-path "test/dinero/*"
      - name: Run Forge Ion tests
        run: forge test --match-path "test/ion/*"
      - name: Run Forge Pendle tests
        run: forge test --match-path "test/pendle/*"
      - name: Run Forge Reservoir tests
        run: forge test --match-path "test/reservoir/*"
